# core/pdf.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib import colors
from pathlib import Path
from datetime import datetime

def build_exec_summary(eri, hist, branches, inv, crm, logo_path: Path, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(out_path), pagesize=A4)
    W, H = A4

    # Header
    y = H - 2*cm
    if logo_path.exists():
        c.drawImage(str(logo_path), 1.5*cm, y-1.6*cm, width=3.2*cm, height=1.6*cm, mask='auto')
    c.setFont("Helvetica-Bold", 18)
    c.drawString(6*cm, y, "EV Sales Optimizer — Executive Summary")
    c.setFont("Helvetica", 10)
    c.drawString(6*cm, y-0.6*cm, datetime.now().strftime("%d %b %Y, %H:%M"))

    # KPIs
    total_leads = len(crm) if crm is not None else 0
    total_stock = int(inv['stock_units'].sum()) if inv is not None else 0
    num_counties = len(eri['county'].unique()) if eri is not None else 0
    num_branches = len(branches) if branches is not None else 0

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1.5*cm, H-4.0*cm, "Key Metrics")
    c.setFont("Helvetica", 11)
    c.drawString(1.7*cm, H-5.0*cm, f"Counties: {num_counties}")
    c.drawString(1.7*cm, H-5.7*cm, f"Branches: {num_branches}")
    c.drawString(9.5*cm, H-5.0*cm, f"Total Leads: {total_leads}")
    c.drawString(9.5*cm, H-5.7*cm, f"Stock Units: {total_stock}")

    # Readiness top/bottom
    if eri is not None and len(eri) > 0:
        top = eri.sort_values("readiness_score", ascending=False).head(5)
        bot = eri.sort_values("readiness_score", ascending=True).head(5)

        c.setFont("Helvetica-Bold", 12)
        c.drawString(1.5*cm, H-7.2*cm, "Top 5 Ready Counties")
        c.setFont("Helvetica", 10)
        y2 = H-7.9*cm
        for _, r in top.iterrows():
            c.drawString(1.7*cm, y2, f"{r['county']}: {int(r['readiness_score'])}")
            y2 -= 0.5*cm

        c.setFont("Helvetica-Bold", 12)
        c.drawString(9.5*cm, H-7.2*cm, "Bottom 5 Ready Counties")
        c.setFont("Helvetica", 10)
        y3 = H-7.9*cm
        for _, r in bot.iterrows():
            c.drawString(9.7*cm, y3, f"{r['county']}: {int(r['readiness_score'])}")
            y3 -= 0.5*cm

    # Footer
    c.setStrokeColor(colors.grey)
    c.line(1.5*cm, 1.8*cm, W-1.5*cm, 1.8*cm)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(1.5*cm, 1.4*cm, "Generated by EV Sales Optimizer — Forecast • Focus • Reallocate • Prove Revenue Uplift")

    c.showPage()
    c.save()
    return out_path
